[features]
seeds = false
[programs.localnet]
voting = "3FNz9W9QSeUWZydZZYR2hHWneLne4civTpecMJGoR84v"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/loopmonkey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
